"""Deterministic phased-plan fixture builder for autopilot tests.

The produced source passes ``validate_autopilot_plan``; the body and control
frontmatter are deterministic so the execution digest is stable.
"""


def plan_source_valid(
    phases: int = 2,
    completed: tuple = (),
    current: int = 1,
    report: str = ".cg-docs/work-reports/example.md",
    status: str = "active",
    extra: str = "",
) -> str:
    lines = [
        "---",
        "artifact-schema-version: 1",
        "date: 2026-01-01",
        'title: "Autopilot Test Plan"',
        f"status: {status}",
        'scope: "Deep"',
        "deviation-policy: ask",
        f"phases: {phases}",
        f"completed-phases: [{', '.join(str(p) for p in completed)}]",
        f"current-phase: {current}",
        f'execution-report: "{report}"',
        "tags: [test]",
        "---",
        "",
        "# Plan: Autopilot Test Plan",
        "",
        "## Objective",
        "",
        "Validate the autopilot plan grammar.",
        "",
        "## Context",
        "",
        "Deterministic phased plan fixture.",
        "",
        "## Requirements",
        "",
        "| ID | Requirement | Source |",
        "|----|-------------|--------|",
        f"| R1 | Cover phases 1 through {phases}. | Contract |",
        "",
    ]
    for phase in range(1, phases + 1):
        lines += [
            f"## Phase {phase}: Phase {phase}",
            "",
            f"### {phase}. Step {phase}",
            "",
            "- **Requirements**: R1",
            "- **Files**: `fixture.py`",
            "- **Details**: Deterministic step body.",
            "- **Test Scenarios**: happy path",
            "- **Tests**: `pytest -q`",
            "- **Acceptance criteria**: Tests pass.",
            "",
        ]
    lines += [
        "## Testing Strategy",
        "",
        "Run focused pytest files.",
        "",
        "## Documentation Checklist",
        "",
        "- [ ] Document strict behavior.",
        "",
        "## Risks & Mitigations",
        "",
        "| Risk | Impact | Mitigation |",
        "|------|--------|------------|",
        "| Drift | Invalid execution | Guard tests. |",
        "",
        "## Out of Scope",
        "",
        "- Generic Markdown parsing.",
        "",
        "## Completion Contract",
        "",
        "### Outcome",
        "",
        "The phased plan validates deterministically.",
        "",
        "### Verification Surface",
        "",
        "| ID | Phase | Evidence Required | Command/Artifact | Required |",
        "|----|-------|-------------------|------------------|----------|",
        f"| V1 | {phases} | Tests pass. | `pytest -q` | yes |",
        "",
        "### Constraints",
        "",
        "| ID | Phase | Constraint | Check |",
        "|----|-------|------------|-------|",
        f"| C1 | {phases} | Deterministic. | Test |",
        "",
        "### Boundaries",
        "",
        "- Allowed: scripts.",
        "",
        "### Iteration Policy",
        "",
        "1. Validate after each implementation step.",
        "",
        "### Blocked-Stop Conditions",
        "",
        "- Required evidence cannot run.",
        "",
    ]
    return "\n".join(lines) + extra
