"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");
const crypto = require("node:crypto");
const { importDev } = require("../legacy-pages.js");
const legacy = path.join(__dirname, "fixtures/docs-redesign/legacy");
const historical = require("./fixtures/docs-redesign/legacy/scripts/rebuild-docs.js");
const sha = value => crypto.createHash("sha256").update(value).digest("hex");
function tree(root) {
  const result = {};
  function walk(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const file = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(file);
      else result[path.relative(root, file)] = sha(fs.readFileSync(file));
    }
  }
  walk(root); return result;
}
function fixture(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "cg-derivation-"));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const source = path.join(root, "source"), producer = path.join(root, "producer"), artifact = path.join(root, "artifact");
  const staging = path.join(root, "staging");
  fs.cpSync(path.join(__dirname, "fixtures/docs-automation/src/basic"), source, { recursive: true });
  fs.cpSync(path.join(legacy, "scripts"), path.join(source, "scripts"), { recursive: true });
  fs.writeFileSync(path.join(source, "docs/index.html"), "<html><body>Canonical home</body></html>");
  fs.cpSync(source, producer, { recursive: true });
  historical.runRebuild(producer, { all: true });
  fs.mkdirSync(artifact);
  fs.cpSync(path.join(producer, "docs"), path.join(artifact, "docs"), { recursive: true });
  fs.copyFileSync(path.join(producer, ".docs-build-metadata.json"), path.join(artifact, ".docs-build-metadata.json"));
  return { source, artifact, staging };
}

test("verified legacy import stages regenerated bytes and never mutates canonical inputs", t => {
  const f = fixture(t), before = tree(f.source);
  importDev(f.source, f.artifact, f.staging);
  assert.deepEqual(tree(f.source), before);
  assert.deepEqual(tree(path.join(f.staging, "docs")), tree(path.join(f.artifact, "docs")));
});

for (const file of ["index.html", "reference.md", "whats-new.md"]) {
  test(`self-consistent forged ${file} is rejected before promotion`, t => {
    const f = fixture(t), before = tree(f.source);
    fs.mkdirSync(f.staging); fs.writeFileSync(path.join(f.staging, "sentinel"), "valid prior output");
    const target = path.join(f.artifact, "docs", file);
    let text = fs.readFileSync(target, "utf8");
    text = file === "index.html" ? text + "forged" : text.replace("<!-- cg:auto:end -->", "forged\n<!-- cg:auto:end -->");
    fs.writeFileSync(target, text);
    const metadataPath = path.join(f.artifact, ".docs-build-metadata.json");
    const metadata = JSON.parse(fs.readFileSync(metadataPath)); metadata.site.files[file] = sha(text);
    fs.writeFileSync(metadataPath, JSON.stringify(metadata));
    assert.throws(() => importDev(f.source, f.artifact, f.staging), /canonical|generated|derivation|expected/i);
    assert.deepEqual(tree(f.source), before);
    assert.equal(fs.readFileSync(path.join(f.staging, "sentinel"), "utf8"), "valid prior output");
  });
}

test("unknown canonical generator code cannot select the legacy contract", t => {
  const f = fixture(t);
  fs.appendFileSync(path.join(f.source, "scripts/rebuild-docs.js"), "\n// unrecognized producer\n");
  assert.throws(() => importDev(f.source, f.artifact, f.staging), /unknown|canonical|producer/i);
});

test("protected legacy implementations remain byte-identical to the independently captured fixtures", () => {
  for (const file of fs.readdirSync(path.resolve(__dirname, "../docs-legacy-v1"))) {
    assert.deepEqual(fs.readFileSync(path.resolve(__dirname, "../docs-legacy-v1", file)), fs.readFileSync(path.join(legacy, "scripts", file)));
  }
});

test("modern producer import and paired composition preserve sources and reject forged output end to end", t => {
  const { modernSource, modernArtifact } = require("./docs-publishing-fixture.js");
  const main = modernSource(), dev = modernSource(), artifact = modernArtifact(dev);
  const work = fs.mkdtempSync(path.join(os.tmpdir(), "cg-pair-"));
  t.after(() => { for (const p of [main, dev, artifact, work]) fs.rmSync(p, { recursive: true, force: true }); });
  const before = [tree(main), tree(dev)];
  const staging = path.join(work, "import"), out = path.join(work, "paired");
  importDev(dev, artifact, staging);
  const composer = require("../assemble-docs-site.js");
  const options = { mainRoot: main, devRoot: dev, devBuild: staging, out, mainSha: "1".repeat(40), devSha: "2".repeat(40) };
  composer.writeCombinedSite(options);
  assert.equal(composer.verifyCombinedSite(out, main, dev, options), 0);
  assert.deepEqual([tree(main), tree(dev)], before);
  const metadata = JSON.parse(fs.readFileSync(path.join(out, "site/channels.json")));
  assert.equal(metadata.channels.development.assets.length, 8);
  assert.match(fs.readFileSync(path.join(out, "site/dev/index.html"), "utf8"), /integrity="sha256-/);
  for (const file of ["index.html", "reference.md", "reference/commands.md", "assets/command-index.json", "assets/search-index.json", "assets/site.js", "assets/docs-search.js"]) {
    const target = path.join(artifact, "docs", file), original = fs.readFileSync(target);
    fs.appendFileSync(target, "\nforged");
    const metaPath = path.join(artifact, ".docs-build-metadata.json"), originalMeta = fs.readFileSync(metaPath);
    const meta = JSON.parse(originalMeta); meta.site.files[file] = sha(fs.readFileSync(target)); fs.writeFileSync(metaPath, JSON.stringify(meta));
    assert.throws(() => importDev(dev, artifact, staging), /canonical expected output/);
    assert.deepEqual([tree(main), tree(dev)], before);
    fs.writeFileSync(target, original); fs.writeFileSync(metaPath, originalMeta);
  }
  // Self-consistent final metadata cannot turn a changed homepage into source proof.
  fs.appendFileSync(path.join(out, "site/index.html"), "forged");
  const metaPath = path.join(out, ".docs-build-metadata.json"), meta = JSON.parse(fs.readFileSync(metaPath));
  meta.site.files["index.html"] = sha(fs.readFileSync(path.join(out, "site/index.html")));
  fs.writeFileSync(metaPath, JSON.stringify(meta));
  assert.throws(() => composer.verifyCombinedSite(out, main, dev, options), /canonical expected output/);
});

test("v2 fingerprints bind absent inputs and generator/runtime code but exclude independently verified indexes", t => {
  const { modernSource } = require("./docs-publishing-fixture.js");
  const root = modernSource(); t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const fingerprint = () => require("../docs-fingerprint.js").fingerprint(root, 2);
  const original = fingerprint();
  for (const file of ["docs/assets/search-index.json", "docs/assets/command-index.json"]) fs.writeFileSync(path.join(root, file), "forged derived output");
  assert.equal(fingerprint(), original);
  const absent = path.join(root, ".github/shared/help-catalog.json"); fs.writeFileSync(absent, "{}");
  assert.notEqual(fingerprint(), original); fs.rmSync(absent);
  fs.appendFileSync(path.join(root, "scripts/docs-search-index.js"), "\n// changed generator\n");
  assert.notEqual(fingerprint(), original);
  assert.throws(() => require("../docs-provenance.js").identifyProducer(root), /code mismatch/);
  fs.writeFileSync(path.join(root, "docs/channels.json"), "{}");
  assert.throws(fingerprint, /reserved/);
});

test("producer version downgrade and extra metadata fields fail before import", t => {
  const { modernSource, modernArtifact } = require("./docs-publishing-fixture.js");
  const root = modernSource(), artifact = modernArtifact(root), staging = path.join(root + "-stage");
  t.after(() => { for (const p of [root, artifact, staging]) fs.rmSync(p, { recursive: true, force: true }); });
  const metaPath = path.join(artifact, ".docs-build-metadata.json"), original = JSON.parse(fs.readFileSync(metaPath));
  for (const change of [meta => { meta.producerContract = "compound-gpid-docs-producer-v1"; meta.fingerprintVersion = 1; },
    meta => { delete meta.producerContract; delete meta.fingerprintVersion; }, meta => { meta.fingerprintVersion = 99; },
    meta => { meta.extra = true; }]) {
    const metadata = structuredClone(original); change(metadata); fs.writeFileSync(metaPath, JSON.stringify(metadata));
    assert.throws(() => importDev(root, artifact, staging), /canonical|downgrade|version|metadata/);
    assert.equal(fs.existsSync(staging), false);
  }
});

test("tagged legacy producer survives import, composition and independent recovery verification", t => {
  const f = fixture(t), { modernSource } = require("./docs-publishing-fixture.js");
  const dev = modernSource(); t.after(() => fs.rmSync(dev, { recursive: true, force: true }));
  fs.cpSync(path.join(legacy, "docs"), path.join(f.source, "docs"), { recursive: true });
  fs.writeFileSync(path.join(f.source, "docs/.nojekyll"), "");
  const producer = path.join(f.source, "../tag-build"); fs.cpSync(f.source, producer, { recursive: true });
  historical.runRebuild(producer, { all: true });
  fs.cpSync(path.join(producer, "docs"), path.join(f.artifact, "docs"), { recursive: true });
  fs.copyFileSync(path.join(producer, ".docs-build-metadata.json"), path.join(f.artifact, ".docs-build-metadata.json"));
  const before = tree(f.source); importDev(f.source, f.artifact, f.staging);
  const options = { mainRoot: f.source, devRoot: dev, mainBuild: f.staging, out: path.join(f.source, "../pair"),
    mainSha: "1".repeat(40), devSha: "2".repeat(40), mainBranch: "dev", mainRef: "v1.2.3.4" };
  const composer = require("../assemble-docs-site.js"); composer.writeCombinedSite(options);
  assert.equal(composer.verifyCombinedSite(options.out, f.source, dev, options), 0);
  assert.deepEqual(tree(f.source), before);
});

test("source readers reject symlinked ancestors before trusting bytes", t => {
  const f = fixture(t), link = path.join(f.source, "../linked");
  fs.symlinkSync(f.source, link, "dir");
  assert.throws(() => require("../docs-source.js").readTree(path.join(link, "docs")), /symbolic|linked/);
  assert.throws(() => require("../docs-provenance.js").identifyProducer(link), /symbolic|linked/);
});
