"""Step7 source-bound support evidence and offline host protocol tests."""
from __future__ import annotations

import copy
import hashlib
import importlib
import importlib.util
import json
import subprocess
from pathlib import Path

import pytest


def support_module():
    """Assert the required implementation exists before importing it."""
    assert importlib.util.find_spec("help.support") is not None, "Step7 support verifier is missing"
    return importlib.import_module("help.support")


def git(root, *args):
    """Run Git only in this owned synthetic history."""
    return subprocess.run(["git", "-C", str(root), *args], check=True,
                          capture_output=True, text=True).stdout.strip()


def write(root, path, content):
    destination = root / path
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(content.encode("utf-8"))


def successful_probes(support):
    """Synthetic success is test-only, never a production evidence writer."""
    return [dict(name=name, arguments=list(support.PROBE_ARGUMENTS),
                 receivedQuerySha256=hashlib.sha256(text.encode()).hexdigest(),
                 outcome="passed") for name, text in support.PROBE_CASES.items()]


@pytest.fixture
def history(tmp_path):
    support = support_module()
    root = tmp_path / "h"
    root.mkdir()
    git(root, "init", "-b", "dev")
    # Per-command identity is confined to the synthetic repository, not git config.
    write(root, ".github/shared/help-catalog.json", json.dumps({
        "sourceDigest": "a" * 64, "commands": [], "workflows": []}))
    write(root, ".github/shared/target-mapping.json", json.dumps({"targets": [
        {"id": platform, "outputPaths": {"commands": directory}}
        for platform, directory in support.PROMPT_ROOTS.items()]}))
    for platform, directory in support.PROMPT_ROOTS.items():
        suffix = ".prompt.md" if platform == "copilot" else ".md"
        write(root, directory + "/cg-help" + suffix, "# Help " + platform + "\n")
    write(root, "scripts/help/query.py", "# query implementation\n")
    write(root, "scripts/help/support.py", "# verifier implementation\n")
    git(root, "add", ".")
    git(root, "-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid",
        "commit", "-m", "subject")
    subject = git(root, "rev-parse", "HEAD")
    bindings = support.subject_bindings(root, subject)
    evidence = dict(schemaVersion=1, subjectCommit=subject, probeCommit=subject,
                    probeTree=git(root, "rev-parse", "HEAD^{tree}"), **bindings)
    evidence["platforms"] = []
    for platform in sorted(support.PROMPT_ROOTS):
        row = dict(platform=platform, **support.platform_bindings(root, subject, platform),
                   staticResults={"asset": "passed", "argumentSource": "passed", "transport": "passed"},
                   runtimeStatus="unverified-no-certified-host", host=None,
                   probeContractVersion=1, probes=[], runAt="2026-09-14T00:00:00Z",
                   reason="No certified host is configured.")
        if platform == "kilo":
            row.update(runtimeStatus="verified", reason="", host={
                "pinnedVersion": "7.4.20", "observedVersion": "7.4.20",
                "pinnedSha256": "b" * 64, "observedSha256": "b" * 64})
            row["probes"] = successful_probes(support)
        evidence["platforms"].append(row)
    return support, root, evidence


def commit(root, message):
    git(root, "add", ".")
    git(root, "-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid", "commit", "-m", message)


def test_step7_support_implementation_exists():
    support_module()


def test_probe_flow_validator_exists():
    assert hasattr(support_module(), "validate_host_flow"), "Step7 host operation/final-output validator is missing"


def test_support_cli_rejects_missing_evidence(tmp_path, capsys):
    verifier = importlib.import_module("cg_verify_help_support")
    assert verifier.main(["--root", str(tmp_path), "--evidence", "missing.json"]) == 2
    assert "verification failed" in capsys.readouterr().err


def test_support_cli_preserves_error_contract_for_stale_catalog(tmp_path, capsys, monkeypatch):
    """A stale catalog must give the documented failure code, not a traceback."""
    verifier = importlib.import_module("cg_verify_help_support")
    write(tmp_path, "support.json", "{}")
    monkeypatch.setattr(verifier.support, "verify_evidence", lambda *_: None)

    def stale(_root):
        raise verifier.catalog.HelpCatalogStaleError("catalog differs from generated bytes")

    monkeypatch.setattr(verifier.catalog, "check_catalog", stale)
    assert verifier.main(["--root", str(tmp_path), "--evidence", "support.json"]) == 2
    assert "verification failed" in capsys.readouterr().err


def test_support_accepts_exact_subject_and_evidence_only_followup(history):
    support, root, evidence = history
    support.verify_evidence(root, evidence)
    write(root, ".cg-docs/work-reports/support.json", json.dumps(evidence))
    write(root, "docs/help-support.md", "Unverified hosts have no runtime claim.\n")
    commit(root, "evidence only")
    support.verify_evidence(root, evidence)


@pytest.mark.parametrize("field", ["subjectCommit", "probeCommit", "probeTree", "sensitiveDigest"])
def test_support_rejects_missing_foreign_identity_or_digest(history, field):
    support, root, evidence = history
    evidence[field] = "f" * (64 if field == "sensitiveDigest" else 40)
    with pytest.raises(ValueError):
        support.verify_evidence(root, evidence)


@pytest.mark.parametrize("field", ["catalogSourceDigest", "catalogSha256", "canonicalPromptSha256",
                                    "targetMappingSha256", "generatedPromptSha256"])
def test_support_rejects_each_stale_platform_binding(history, field):
    support, root, evidence = history
    evidence["platforms"][0][field] = "f" * 64
    with pytest.raises(ValueError, match="binding"):
        support.verify_evidence(root, evidence)


@pytest.mark.parametrize("path", ["scripts/help/query.py", "scripts/help/new.py",
                                  ".github/prompts/cg-help.prompt.md",
                                  ".kilo/commands/cg-help.md"])
@pytest.mark.parametrize("committed", [False, True])
def test_support_rejects_changed_or_added_bound_paths(history, path, committed):
    support, root, evidence = history
    write(root, path, "changed bytes\n")
    if committed:
        commit(root, "changed bound implementation")
    with pytest.raises(ValueError, match="sensitive"):
        support.verify_evidence(root, evidence)


def test_support_rejects_nonancestor_subject(history):
    support, root, evidence = history
    git(root, "checkout", "--orphan", "unrelated")
    write(root, "unrelated.txt", "different history\n")
    commit(root, "unrelated")
    with pytest.raises(ValueError, match="ancestor"):
        support.verify_evidence(root, evidence)


def test_support_rejects_existing_default_checkout_instead_of_exact_subject(history):
    support, root, evidence = history
    write(root, "default-only.txt", "default branch moved\n")
    commit(root, "default branch differs from certified subject")
    evidence["probeCommit"] = git(root, "rev-parse", "HEAD")
    with pytest.raises(ValueError, match="Probe commit"):
        support.verify_evidence(root, evidence)


@pytest.mark.parametrize("mutation", ["failed", "unverified-kilo", "host-hash", "host-version",
                                       "missing-probe", "failed-probe", "fingerprint", "static",
                                       "unknown", "raw-query", "duplicate", "future-schema", "date"])
def test_support_status_schema_and_certification_fail_closed(history, mutation):
    support, root, evidence = history
    row = next(item for item in evidence["platforms"] if item["platform"] == "kilo")
    if mutation == "failed":
        row["runtimeStatus"] = "failed"
    elif mutation == "unverified-kilo":
        row.update(runtimeStatus="unverified-no-certified-host", host=None, probes=[], reason="absent")
    elif mutation == "host-hash":
        row["host"]["observedSha256"] = "c" * 64
    elif mutation == "host-version":
        row["host"]["observedVersion"] = "7.4.21"
    elif mutation == "missing-probe":
        row["probes"].pop()
    elif mutation == "failed-probe":
        row["probes"][0]["outcome"] = "failed"
    elif mutation == "fingerprint":
        row["probes"][0]["receivedQuerySha256"] = "e" * 64
    elif mutation == "static":
        row["staticResults"]["transport"] = "failed"
    elif mutation == "unknown":
        row["runtimeStatus"] = "unknown"
    elif mutation == "raw-query":
        row["query"] = "secret input"
    elif mutation == "duplicate":
        evidence["platforms"][0] = copy.deepcopy(row)
    elif mutation == "date":
        row["runAt"] = "not UTC"
    else:
        evidence["schemaVersion"] = 2
    with pytest.raises(ValueError):
        support.verify_evidence(root, evidence)


@pytest.mark.parametrize("received", ["$ARGUMENTS", "", "plan review ; normalized"])
def test_probe_rejects_literal_missing_or_normalized_query(received):
    support = support_module()
    receipt = successful_probes(support)[2]
    receipt["receivedQuerySha256"] = hashlib.sha256(received.encode()).hexdigest()
    with pytest.raises(ValueError, match="fingerprint"):
        support.validate_probe(receipt)
